# Generated by Django 5.1.4 on 2024-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True, max_length=1000)),
                ('Due_date', models.DateField(blank=True, null=True)),
                ('Tags', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('OPEN', 'Open'), ('WORKING', 'Working'), ('PENDING REVIEW', 'Pending Review'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
            ],
        ),
    ]
